name: STM32 CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stm32-ci:
    runs-on: ubuntu-latest

    container:
      image: therisktaker/arm-none-eabi-14.2-and-tools:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: stm32/h745_fmc_udp
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=cmake/arm-gcc-toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build firmware
        working-directory: stm32/h745_fmc_udp
        run: |
          cmake --build build -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: h745_firmware
          path: |
            stm32/h745_fmc_udp/build/*.elf
            stm32/h745_fmc_udp/build/*.bin
            stm32/h745_fmc_udp/build/*.hex
            stm32/h745_fmc_udp/build/*.map
