name: Build and Test STM32 Project

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container:
      image: makarpi/stm32cmakegcc:v1.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build STM32 firmware
        working-directory: stm32/h745_fmc_udp
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/arm-gcc-toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          ninja -C build

      - name: Upload STM32 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32_h745_firmware
          path: stm32/h745_fmc_udp/build/*.hex

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04  # lekki obraz na hostowe testy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake ninja-build

      - name: Build unit tests (Unity)
        working-directory: stm32/h745_fmc_udp/tests
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=gcc
          ninja -C build

      - name: Run unit tests
        working-directory: stm32/h745_fmc_udp/tests
        run: ./build/bin/run_tests